### ISSUE TITLE
ref={register} errors in CH6

### ISSUE THREAD

**Issue by shuangxiaoyao** [PacktPublishing/ASP.NET-Core-5-and-React-Second-Edition#11]
Multiple places  **ref={register}**  with following errors: Header.tsx. AskPage.tsx, etc.

Type 'UseFormRegister<FormData>' is not assignable to type 'LegacyRef<HTMLInputElement> | undefined'.
  Type 'UseFormRegister<FormData>' is not assignable to type '(instance: HTMLInputElement | null) => void'.
    Types of parameters 'name' and 'instance' are incompatible.
      Type 'HTMLInputElement | null' is not assignable to type '"title" | "content"'.
        Type 'null' is not assignable to type '"title" | "content"'.

**Comment by abase0001** [comment]
I met the same error. If you installed react-hook-form v7.1.1, you can refer to the author's example.
https://codesandbox.io/s/react-hook-form-get-started-ts-5ksmm?file=/src/index.tsx

**Comment by carlrip** [comment]
The API in React Hook Form has changed a little since the book was published. You can install v6 as follows if you want to use the code from the book:

```
npm i react-hook-form@6.15.4
```

If you want to use v7 of React Hook Form, see the following link for the differences:

[https://react-hook-form.com/migrate-v6-to-v7/](https://react-hook-form.com/migrate-v6-to-v7/)

For the code in the book, you’ll need to change how the `register` function is called on the JSX elements and how the `errors` state variable is destructured from `useForm`.

Hope this helps.

**Comment by Jay-study-nildana** [comment]
This evening, I was stumped by this for a while. putting the full code if it helps somebody.

      <form onSubmit={handleSubmit}>
        <input
          {...register("search")} defaultValue={criteria}
          placeholder="type here"
          type="text"
        />
      </form>
