### ISSUE TITLE
Compiling error with "ref" attribute - Chapter 6 - Header.tsx

### ISSUE THREAD

**Issue by linhtch90** [PacktPublishing/ASP.NET-Core-5-and-React-Second-Edition#19]
https://github.com/PacktPublishing/ASP.NET-Core-5-and-React-Second-Edition/blob/master/chapter-06/finish/frontend/src/Header.tsx

![image](https://user-images.githubusercontent.com/67230802/120013601-23a32600-c00b-11eb-8001-241b4b5164fd.png)

**Comment by Kalcooney** [comment]
Try ref={...register} else downgrade react-hook-form to the version the book uses.

**Comment by carlrip** [comment]
Yep, as per the comment above, the API in React Hook Form has changed a little since the book was published. You can install v6 as follows if you want to use the code from the book:

```
npm i react-hook-form@6.15.4
```

If you want to use v7 of React Hook Form, see the following link for the differences:

https://react-hook-form.com/migrate-v6-to-v7/

For the code in the book, you’ll need to change how the `register` function is called on the JSX elements and how the `errors` state variable is destructured from `useForm`.

Hope this helps.
